<script lang="ts">
    export const mainDesc = " asdsa";
    import '../styles/main.css'
</script>

<style>

    @font-face {
        font-family: 'Luticaprofile'; /*font 이름*/
        font-style: 'normal'; /* font 스타일 정의 (기울임, 일반) */
        font-weight: 400; /* font 굵기 정의 */
        /* 브라우저&디바이스 환경에 따른 font 파일 위치 정의 */
        src: url('font/gyonggicheonn.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */ url('font/gyonggicheonn_bold.otf') format('otf'),
            /*  Modern Browsers */ url('gyonggicheonn_bold.otf') format('otf'), /* Modern Browsers */ url('font/gyonggicheonn.ttf') format('truetype'),
            /* Safari, Android, iOS */
            
    }

    .maincard__wrap{
        height:100%
    }
    .maincard__wrap__main{
        display:flex;
        justify-content: space-evenly;
        align-items: center;
        height: 100%;
    }
    .maincard__border{
        padding-bottom : min(100%,500px);
        position: relative;
        width: min(809px,100%);
        border: #555555 1px solid;
        border-radius: 2%;        
    }
    .shadow-drop-lr {
        -webkit-animation: shadow-drop-lr 0.4s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
        animation: shadow-drop-lr 0.4s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
    }
    .card__inside{
        border-radius: 2%;

        position:absolute;
        display: flex;
        flex-direction: column;
        height: 100%;
        width: 100%;
        align-content: space-between;
        justify-content: space-between;
        align-items: flex-start;
        background : url('/profile_a.png');
        background-size: cover;
    }
    .nick_name{
        color : white;
        font-family:'Luticaprofile'
    }
    .stack_name{
        color : white;
        font-family:'Luticaprofile';
        margin: 4px
    }
    .article_div{
        color : white;
        font-family:'Luticaprofile';
        display:flex;
        flex-direction:column;
        padding :2%;
    }
    .stack{
        display:flex;
        flex-direction: column;
    }
    .main_container{
        margin-left : 5%;
        margin-top : 5%;
        padding : 2%;
    }
    .article > a{
        text-decoration : none;
        color:white;
    }
    .nick_name > a{
        text-decoration : none;
        color:white;
    }
    /* ----------------------------------------------
    * Generated by Animista on 2024-2-2 1:17:5
    * Licensed under FreeBSD License.
    * See http://animista.net/license for more info. 
    * w: http://animista.net, t: @cssanimista
    * ---------------------------------------------- */
    
    /**
    * ----------------------------------------
    * animation shadow-drop-lr
    * ----------------------------------------
    */
    @-webkit-keyframes shadow-drop-lr {
        0% {
            -webkit-box-shadow: 0 0 0 0 rgba(0, 0, 0, 0), 0 0 0 0 rgba(0, 0, 0, 0);
            box-shadow: 0 0 0 0 rgba(0, 0, 0, 0), 0 0 0 0 rgba(0, 0, 0, 0);
        }
        100% {
            -webkit-box-shadow: -12px 0 20px -12px rgba(0, 0, 0, 0.35), 12px 0 20px -12px rgba(0, 0, 0, 0.35);
            box-shadow: -12px 0 20px -12px rgba(0, 0, 0, 0.35), 12px 0 20px -12px rgba(0, 0, 0, 0.35);
        }
    }
    @keyframes shadow-drop-lr {
        0% {
            -webkit-box-shadow: 0 0 0 0 rgba(0, 0, 0, 0), 0 0 0 0 rgba(0, 0, 0, 0);
            box-shadow: 0 0 0 0 rgba(0, 0, 0, 0), 0 0 0 0 rgba(0, 0, 0, 0);
        }
        100% {
            -webkit-box-shadow: -12px 0 20px -12px rgba(0, 0, 0, 0.35), 12px 0 20px -12px rgba(0, 0, 0, 0.35);
            box-shadow: -12px 0 20px -12px rgba(0, 0, 0, 0.35), 12px 0 20px -12px rgba(0, 0, 0, 0.35);
        }
    }
</style>
<div class="maincard__wrap">
    <div class="maincard__wrap__main">
        <div class="maincard__border shadow-drop-lr">
            <div class="card__inside">
                <!-- 이하 카드 본문 -->
                <div class="main_container">
                    <div>
                        <h3 class = "nick_name" style="margin-bottom : 1%">
                            Software Developer
                        </h3>
                        <h4 class = "nick_name" style="margin:0">
                            <a href="https://kr.conquerx2.com/">Nano Interactive</a>
                        </h4>
                        <h1 class = "nick_name">
                            <a href="https://github.com/LuticaCANARD">Lutica_CANARD</a>
                        </h1>
                    </div>
                    <div class = "stack">
                        <p1 class = "stack_name">
                            Node.js
                        </p1>
                        <p3 class = "stack_name">
                            C#, Unity, Svelte, PostgreSQL, Redis
                        </p3>
                    </div> 
                </div>
                <div class="article_div">
                    <p1 class= "article">
                        I'm Living in <a href="https://maps.app.goo.gl/393ewhYvVzh1f6qQ6">paju</a>, nearby <a href="https://maps.app.goo.gl/jSAL18mFud9hi42k7">Seoul, Korea.</a>
                    </p1>
                    <p2 class= "article">
                        This card is using <a href="https://gongu.copyright.or.kr/gongu/wrt/wrt/view.do?wrtSn=13288411&menuNo=200195">경기천년제목체B</a>
                    </p2>

                </div>
            </div>
        </div>
    </div>
</div>