<script lang="ts">
    export const mainDesc = " asdsa";
    import '../styles/main.css'
</script>

<style>
    .maincard__wrap{
        height:100%
    }
    .maincard__wrap__main{
        display:flex;
        justify-content: space-evenly;
        align-items: center;
        height: 100%;
    }
    .maincard__border{
        padding-bottom : min(66%,300px);
        position: relative;
        width:468px;
        border: #939393 1px solid;
        border-radius: 10px;
        background-color:white;
        
    }
    .shadow-drop-lr {
        -webkit-animation: shadow-drop-lr 0.4s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
        animation: shadow-drop-lr 0.4s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
    }
    .card__inside{
        position:absolute;
        display: flex;
        flex-direction: column;
        height: 100%;
        width: 100%;
        align-content: space-between;
        justify-content: space-around;
        align-items: center;
    }
    /* ----------------------------------------------
    * Generated by Animista on 2024-2-2 1:17:5
    * Licensed under FreeBSD License.
    * See http://animista.net/license for more info. 
    * w: http://animista.net, t: @cssanimista
    * ---------------------------------------------- */
    
    /**
    * ----------------------------------------
    * animation shadow-drop-lr
    * ----------------------------------------
    */
    @-webkit-keyframes shadow-drop-lr {
        0% {
            -webkit-box-shadow: 0 0 0 0 rgba(0, 0, 0, 0), 0 0 0 0 rgba(0, 0, 0, 0);
            box-shadow: 0 0 0 0 rgba(0, 0, 0, 0), 0 0 0 0 rgba(0, 0, 0, 0);
        }
        100% {
            -webkit-box-shadow: -12px 0 20px -12px rgba(0, 0, 0, 0.35), 12px 0 20px -12px rgba(0, 0, 0, 0.35);
            box-shadow: -12px 0 20px -12px rgba(0, 0, 0, 0.35), 12px 0 20px -12px rgba(0, 0, 0, 0.35);
        }
    }
    @keyframes shadow-drop-lr {
        0% {
            -webkit-box-shadow: 0 0 0 0 rgba(0, 0, 0, 0), 0 0 0 0 rgba(0, 0, 0, 0);
            box-shadow: 0 0 0 0 rgba(0, 0, 0, 0), 0 0 0 0 rgba(0, 0, 0, 0);
        }
        100% {
            -webkit-box-shadow: -12px 0 20px -12px rgba(0, 0, 0, 0.35), 12px 0 20px -12px rgba(0, 0, 0, 0.35);
            box-shadow: -12px 0 20px -12px rgba(0, 0, 0, 0.35), 12px 0 20px -12px rgba(0, 0, 0, 0.35);
        }
    }
</style>
<div class="maincard__wrap">
    <div class="maincard__wrap__main">
        <div class="maincard__border shadow-drop-lr ">
            <div class="card__inside">
                <!-- 이하 카드 본문 -->
                <p1>{mainDesc}</p1>
            </div>
        </div>
    </div>
</div>